- demos/browser/src/App.tsx
- src/apollo/index.ts
- src/castor/index.ts
- src/domain/models/DID.ts
- src/mercury/didcomm/DIDResolver.ts
- src/mercury/didcomm/SecretsResolver.ts
- src/mercury/didcomm/Wrapper.ts
- src/mercury/index.ts
- src/pollux/index.ts
- src/prism-agent/Agent.ts
- tests/domain/did.test.ts
Adding function to simplify Agent creation.
Other changes:
- Changed Browser demo to use new function.
- Added `DID.from` function to enable simple DID usage
- Added missing index files from core components and updated imports
- Fixed some comment typos
https://input-output.atlassian.net/browse/ATL-4057
> feat(Agent): add initialize function

- src/domain/buildingBlocks/Pluto.ts
We are about to release prism 2.6 and as reported by a user we have missed introducing the breaking change in Pluto. Despite Pluto is not part of our bundle anymore, we do cause disruption with existing users and the correct is to apply the breaking change.
Only positive thing is that 2.5.0 is part of 2.6 prism release which is not yet released, its a draft release.
This PR does not introduce the breaking change but just applies the configuration and doc changes.
- X25519 keys were wrongly set as EC (elliptic) key types which is wrong. EC25519 + Secp256k1 belong to EC key type, X25519 should have Curve25519 instead to be valid. If you previously had a key stored as EC (x25519) changing that keyType to KeyTypes.X25519 (Curve25519).
- As we have introduced new credential types we have also …
> feat(docs): add pluto breaking changes in the JSDOC comments

- demos/browser/src/App.tsx
- src/prism-agent/Agent.Invitations.ts
- src/prism-agent/Agent.ts
Extending acceptInvitation to handle both OOB and Prism invitations.
Marking acceptDIDCommInvitation as deprecated.
Updating Browser Demo to use acceptInvitation
https://input-output.atlassian.net/browse/ATL-4064
> feat: extending Agent.acceptInvitation to handle OOB + Prism

- .github/workflows/ci.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/release-docs.yml
- .github/workflows/release.yml
- .releaserc.yml
- package-lock.json
- package.json
> chore: publish to npm registry under @atala group

- .github/workflows/e2e-tests.yml
> test: update e2e env vars

- demos/browser/src/App.tsx
- demos/node/src/index.ts
Simply changing peer dids in the demo to use the last encoding in the mediators peerDID which is adding an extra service to use websockets as transport over http.
N/A
> fix: Update demos to use the new Mediator peer did

- src/domain/models/keyManagement/PrivateKey.ts
- tests/apollo/keys/Ed25519.test.ts
- tests/apollo/keys/Secp256k1.test.ts
- tests/apollo/keys/X25519.test.ts
BREAKING CHANGE: `PrivateKey.index` now returns `number | undefined`
`PrivateKey.index` was returning a `string` it's possible where that's being used (ie Pluto) will need to handle the new `number | undefined` type
https://input-output.atlassian.net/browse/ATL-6298
> refactor: PrivateKey.index to return an integer | undefined

- src/domain/models/errors/Agent.ts
- src/pollux/models/AnonCredsVerifiableCredential.ts
- src/prism-agent/helpers/ProtocolHelpers.ts
- src/prism-agent/protocols/other/BasicMessage.ts
Updating a couple of known Typos.
These are technically internal to the SDK so shouldn't break downstream, but as they are exported it's possible.
- update classname `InvalidBasicMEssageBodyError` to `InvalidBasicMessageBodyError`
- update property of `AnonCredsCredentialProperties`: `signasture` to `signature`
https://input-output.atlassian.net/browse/ATL-6313
> fix: typos InvalidBasicMEssageBodyError and signasture

- src/castor/resolver/PeerDIDResolver.ts
- src/peer-did/PeerDID.ts
- tests/agent/Agent.test.ts
- tests/agent/mocks/CastorMock.ts
- tests/agent/mocks/ConnectionManagerMock.ts
- tests/castor/PeerDID.test.ts
- tests/mercury/Mercury.test.ts
- tests/mercury/didcomm/SecretsResolver.test.ts
> fix: key's id name according to the DID Peer new specs #126

- src/pollux/models/JWTVerifiableCredential.ts
- tests/pollux/Pollux.test.ts
Fixes https://github.com/input-output-hk/atala-prism-wallet-sdk-ts/issues/170
> fix: Recover JTI field correctly. Allowing to regenerate the original JWT string

- .github/workflows/e2e-tests.yml
The release branches never are included in a pull request, they exist by cherry-picking and then we deploy the version and as soon as the tags have been pushed by the CI task the release branch can be removed if needed.
I have identified that if we don't have a pull request open the CI pipeline for e2e tests will not be running the build, pack + install.
> fix: Removing the if condition in CI pipeline for release branches

- src/pluto/rxdb/Store.ts
Found a bug in our pluto implementation which is leading to databases not being usable. The user's in the browser usually would setup a single database name and work on that single DB. RXDB is not allowing that because second time u create the database it will already exist.
This fixes the issue.
No JIRA Ticket.
- [] My PR follows the contribution guidelines of this project
- [] My PR is free of third-party dependencies that don't comply with the [Allowlist](https://toc.hyperledger.org/governing-documents/allowed-third-party-license-policy.html#approved-licenses-for-allowlist)
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- …
> fix: db cannot be created twice with the same name which crashes demos

- .vscode/launch.json
- integration-tests/e2e-tests/src/steps/EdgeAgentSteps.ts
- integration-tests/e2e-tests/src/steps/LifecycleSteps.ts
- src/prism-agent/connectionsManager/ConnectionsManager.ts
- src/prism-agent/helpers/Task.ts
- src/prism-agent/mediator/BasicMediatorHandler.ts
- src/prism-agent/types/index.ts
- tests/agent/Agent.ConnectionsManager.test.ts
- tests/agent/mocks/ConnectionManagerMock.ts
> fix: e2e issues with latest websocket changes

- index.d.ts
Simple fix that fixes the types from not being available to users that don't have all the resource.
We had already detected this but the change is in a PR that is not yet merged. So I prefer not to rush and include  the change directly in this small PR. 
This change should go out as soon as possible.
> fix: type references are lost in the package.

- src/pollux/models/JWTVerifiableCredential.ts
- tests/pollux/Pollux.test.ts
In our current 2.12 release we have introduced multiple breaking changes into the JWT classes and https://github.com/input-output-hk/atala-prism-wallet-sdk-ts/pull/175 that PR now has some conflicts.
The JWT specification states issuance and expiration dates as numbers, and we were generating dates using the number of seconds not ms
> fix: add compliant dates not in ms, but in seconds.

- docs/README.mdx
- docs/sdk/README.md
- docs/sidebars.js
- package.json
- Updates the items in the sidebar from `sdk/Something` to `Something`
- Adds a redirect `README.mdx` from `/atala-prism-wallet-sdk-ts/` to `/atala-prism-wallet-sdk-ts/sdk` (simple workaround to about 404 if the person tries to enter manually the url)
- README.md is back as part of `docs/sdk/` folder
- Undo `docs` script change
> docs: updates documentation to use sdk folder

- externals/run.sh
Fixes issue with sed commands, we have been having some regression issues around how libraries are built.
When wasm-pack builds the output for us, is generates :
```
if (typeof input === 'undefined') {
input = new URL('anoncreds_bg.wasm', import.meta.url);
}
```
This peace of code is invalid and should be removed by the build command. 
We do this by running sed.
Please follow this article for more information: https://stackoverflow.com/questions/12696125/sed-edit-file-in-place
But we need to run different code depending on where the build is running from.
> fix: Compatibility issues with osx and unix platforms around the sed

- .github/workflows/e2e-tests.yml
Master `branch` has been renamed to `main`.
This PR fixes the event that trigger the e2e execution
> ci: changes e2e workflow trigger

- src/pollux/Pollux.ts
- src/pollux/utils/Bitstring.ts
just fixing and using a custom class now bitstring which is more precisely determining if the revocation is true or false. Earlier was checking that the revocation was not 0 but this is more concrete.
> fix: create custom class to verify bitstring position more precisely.

- .github/workflows/e2e-tests.yml
- integration-tests/e2e-tests/yarn.lock
- package-lock.json
- package.json
- postinstall.sh
- preinstall.sh
A recent issue recently was introduced when we added the preinstall and postinstall scripts.
Yarn does not handle the paths very well when installing the package from a higher directory.
This PR aims to solve the issue with the package hooks, on top of the previous the patch file was not being included.
This should make the CI fail in its next step but not hooks!
> fix: e2e issues fix

- src/domain/models/Message.ts
Adding base64 and base64url fallback in didcomm attachment extract fn's. earlier we were using Buffer which was able to handle cases where we get base64url and we should be getting base64.
> fix: attachment encoding fallback base64 + base64url by default

- integration-tests/e2e-tests/features/backup.feature
- integration-tests/e2e-tests/src/abilities/WalletSdk.ts
- integration-tests/e2e-tests/src/steps/EdgeAgentSteps.ts
- integration-tests/e2e-tests/src/steps/LifecycleSteps.ts
- integration-tests/e2e-tests/src/workflow/EdgeAgentWorkflow.ts
> test: add backup e2e scenarios

- src/castor/Castor.ts
- src/castor/resolver/LongFormPrismDIDResolver.ts
- src/domain/models/keyManagement/Key.ts
- src/pollux/utils/JWT.ts
- tests/castor/PrismDID.test.ts
- tests/fixtures/keys.ts
Multiple fixes around did resolution:
Bug1: Resolving a PrismDID was overwriting the key ids with our own value
fix: src/castor/resolver/LongFormPrismDIDResolver.ts line 124
use the `key.id` instead of generating our own with `getUsageId`
Bug2: Creating a PrismDID with multiple `issuing keys` only encodes one, as the key ids conflict.
fix: src/castor/Castor.ts line 146
create the `id` from both the `usage` and the `index`
Bug3: JWT verify required the encoded verification methods to be in order with the signing key first, otherwise would fail
fix: attempt verification with all verification methods, as no way of determining which was used
> fix(Castor): createPrismDID and resolveDID key id conflicts

- integration-tests/e2e-tests/package.json
- integration-tests/e2e-tests/yarn.lock
- package-lock.json
- src/mercury/didcomm/Wrapper.ts
While debugging the repeated message from Mediator we found out the cause of it. This PR fixes this long time issue.
Fixes ATL-7354
Unit tests:
Integration tests:
> fix: attachment descriptor parameters

- CONTRIBUTING.md
fixes : https://github.com/hyperledger/identus-edge-agent-sdk-ts/issues/251
Problem: signing + sign-off are not common for many open-source projects. Barrier to entry
Solution: document it to make it easier to get started
> docs: add commit signing notes to CONTRIBUTING

- externals/run.sh
> fix: external build update for new generated code

- README.md
The current README gives very little info on what's needed for a Pluto implementation
Changes:
- mentioned that it's Pluto.Store you need to implement (not Pluto any more)
- started a "community implementations" section, and linked `pluto-encrypted` work
> docs: link pluto-encrypted as reference implementation

- release-dev.config.js
- release-prod.config.js
Semantic release config still referencing "master" branch.
Changed to "main"
> fix: main branchname in semantic release config

- .github/workflows/e2e-tests.yml
Apollo is not part of GHCR anymore. Removing authentication node setup
> ci: removes @hyperledger scope auth

- .github/workflows/ci.yml
- .github/workflows/e2e-tests.yml
Sets the workflow files to use node lts version in e2e
> ci: set action to use node lts

- publish.sh
> ci: fixes release script

- integration-tests/e2e-tests/src/abilities/WalletSdk.ts
- integration-tests/e2e-tests/src/workflow/EdgeAgentWorkflow.ts
fix e2e tests and module resolution issue with the new sdk
> fix: sdk module resolution issues

- demos/next/src/components/Message.tsx
- src/domain/models/errors/Agent.ts
- src/edge-agent/connectionsManager/ConnectionsManager.ts
- src/edge-agent/helpers/ProtocolHelpers.ts
- src/edge-agent/mediator/BasicMediatorHandler.ts
- src/edge-agent/protocols/ProtocolTypes.ts
- src/edge-agent/protocols/other/ProblemReport.ts
- src/edge-agent/protocols/pickup/PickupRunner.ts
- src/edge-agent/protocols/types.ts
- tests/agent/protocols/pickup/PickupRunner.test.ts
- tests/fixtures/messages/index.ts
Adding the error reporting protocol as requested in ATL-5914, added one minor test and demo app which I manually tested.
> fix: integrating error reporting protocol 

- integration-tests/e2e-tests/src/abilities/WalletSdk.ts
- integration-tests/e2e-tests/src/steps/EdgeAgentSteps.ts
- integration-tests/e2e-tests/src/workflow/EdgeAgentWorkflow.ts
- src/mercury/didcomm/Wrapper.ts
- src/pollux/AnoncredsLoader.ts
- src/pollux/Pollux.ts
fix e2e tests not working due to some incompatibilities. We've proven the SDK works in the needed environments but for some reason we were unable to run e2e until this fixes have been implemented
> fix: e2e cucumber import

- .github/workflows/e2e-tests.yml
- integration-tests/e2e-tests/package.json
- integration-tests/e2e-tests/yarn.lock
- Add dispatch to identus-integration repository
- Upgrades serenity-js dependency to be compatible with node 20
> test: adds dispatch to integration repo

- README.md
Fixes: https://github.com/hyperledger/identus-edge-agent-sdk-ts/issues/295
This PR is designed to make the docs more accessible
- link to docs website
- group the headings hierarchically more clearly
- simplify the headings
- less words
- consistent labels (demo everywhere not demo/sample)  
- remove filler text
> docs: link docs, refactor README.md

- package-lock.json
- package.json
Ran `npm audit fix` to remove a few vulns.
Also added @rollup/rollup-linux-x64-gnu dev dependency, which appears to be needed on linux systems.
> chore: needed @rollup/rollup-linux-x64-gnu and audit fix

- package-lock.json
- package.json
Fixing `@rollup/rollup-linux-x64-gnu` dependency breaking non-linux platform installs
> chore: fixing rollup platform dependency

- integration-tests/e2e-tests/package.json
e2e workflows are failing because tests package.json is pointing at a tarball that doesn't exist
> fix: e2e workflows misnamed package

- package-lock.json
- package.json
- src/edge-agent/didcomm/HandleOOBInvitation.ts
Adding this change by default in the SDK will allow me to run a smooth demo. 
During the development of the demo I was missing something and I found out that in our SDK, after parsing a OOB message we stored it but didn't emit the new message event.
This directly affects how people use the code, is needed to make the Hyperledger workshop smoother and not have people build the SDK from source!
> fix: adding esbuild also as optional missing dependency

- src/pluto/rxdb/collections.ts
- src/pluto/rxdb/index.ts
exporting **Pluto** models to make them available outside SDK and make it easier to implement a compatible store.
> fix: export Pluto models

- demos/next-sdjwt-workshop/src/steps/Step3.tsx
- demos/next-sdjwt-workshop/src/steps/Step4.tsx
- demos/next-sdjwt-workshop/src/steps/Step6.tsx
> fix: add listener async + wait time for presentation verified

- demos/next-oidc/src/components/OOB.tsx
- demos/node/README.md
- demos/node/package-lock.json
- demos/node/package.json
- demos/node/src/cli/app.ts
- demos/node/src/cli/asyncPrompt.ts
- demos/node/src/cli/basePrompt.ts
- demos/node/src/cli/index.ts
- demos/node/src/cli/inputPrompt.ts
- demos/node/src/cli/routing.ts
- demos/node/src/cli/selectPrompt.ts
- demos/node/src/cli/state.ts
- demos/node/src/index.ts
- demos/node/src/sdkFns/connections/index.ts
- demos/node/src/sdkFns/connections/listConnections.ts
- demos/node/src/sdkFns/didcommStart.ts
- demos/node/src/sdkFns/index.ts
- demos/node/src/sdkFns/inputOOB.ts
- demos/node/src/sdkFns/messages/acceptCredentialOffer.ts
- demos/node/src/sdkFns/messages/listMessages.ts
- demos/node/src/sdkFns/messages/presentationRequest.ts
- demos/node/src/sdkFns/messages/processCredentialIssue.ts
- demos/node/src/sdkFns/resolveDID.ts
- demos/node/src/sdkFns/updateMediatorDID.ts
- demos/node/tsconfig.json
Adding a new demo, transpiling TS into node, giving us a simple CLI.
Not feature complete, currently handles Agent start, mediation, OOB connection, Credential issuance.
This demo is heavily focused on SDK integration, with minimal app frameworking.
Using to demonstrate functionality use, and generate feedback / conversations for improvements.
> docs: adding new demo for TS -> node

- tests/pluto/Pluto.Migrations.test.ts
Moving tests away from old style chai / sinon implementation to vitest.
Slight simplification to use specific models instead of using the Repositories to generate them.
> test: Pluto.migrations updating to vi

- .github/workflows/ci.yml
actions/upload-artifact and actions/download-artifact have been deprecated and need updated.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> chore: update actions

- src/domain/models/Message.ts
- src/domain/models/MessageAttachment.ts
- src/edge-agent/protocols/pickup/PickupRunner.ts
- src/mercury/didcomm/Wrapper.ts
- src/mercury/forward/ForwardMessage.ts
- tests/domain/message.test.ts
Fixing the mutation of json attachments into data property.
For the sake of backwards compatibility with existing dbs I've left the comparison logic for existing messages, and just changed the code so all new messages will correctly use the `json` property
BREAKING CHANGES:
- AttachmentDescriptor will now only knowingly accept body's with `json` property.
> feat: update DIDComm json message types

- src/plugins/internal/dif/PresentationVerify.ts
- tests/plugins/dif/PresentationVerify.test.ts
Fixes the issue that @curtis-h spotted while refactoring to pollux plugins. During verification there's a loop and we were not properly validating all the edge cases properly + the code was hard to understand.
Have improved the verification process to make it easier to understand, there's many things to fix in there but have focused mainly on the loop and basic error handling.
All the tests are working
> fix: improving presentation exchange verification flow

- .github/CODEOWNERS
- CONTRIBUTING.md
- DCO.md
- MAINTAINERS.md
- README.md
- SECURITY.md
Starting the link updates for the repo change.
> docs: updating links to new repos

- src/pluto/rxdb/Store.ts
Simple PR tto add a deprecation warning, we are transitioning into not bundling  RXDB store wrapper for Pluto in our SDK, but replace this with good documentation on how to use the agent, etc.
> fix: add deprecation warning for rxdb

- demos/node/src/sdkFns/didcommStart.ts
- src/domain/buildingBlocks/Pluto.ts
- src/pluto/Pluto.ts
- src/pluto/rxdb/Store.ts
Updating Pluto to extend Startable, which was previously worked around to avoid a breaking change.
Also updated `Store.clear` function to fully remove persistent state and updated node demo accordingly.
BREAKING CHANGE:
Pluto.stop is now a required function
> feat(Pluto)!: updating Pluto to extend Startable

- docs/sidebars.js
The hyperledger-identus/docs CI fails after updating submodules
It looks like after refactoring, the `sdk/classes/Pollux` was wiped or moved
[Link to the failed CI job](https://github.com/hyperledger-identus/docs/actions/runs/13922450601/job/38958667208#step:4:41)
> docs: sdk/classes/Pollux is removed from the sidebars.js

- src/domain/models/VerifiableCredential.ts
- src/domain/utils/JWT.ts
- src/plugins/internal/dif/PresentationRequest.ts
- src/plugins/internal/dif/PresentationVerify.ts
- src/plugins/internal/dif/types.ts
- src/plugins/internal/oea/sdjwt/CredentialOffer.ts
- src/pollux/models/JWTVerifiableCredential.ts
- src/pollux/models/SDJWTVerifiableCredential.ts
- src/pollux/utils/jwt/CreateSDJWT.ts
- src/pollux/utils/jwt/SDJWT.ts
- tests/fixtures/credentials/jwt.ts
- tests/plugins/dif/PresentationRequest.test.ts
- tests/plugins/dif/PresentationVerify.test.ts
This PR ensures compliance with the  [DIF Presentation exchange protocol V2](https://identity.foundation/presentation-exchange/spec/v2.1.1)
Added fixes to properly validate submissions recursively using descriptor_item format and nested_paths.
Presentation Submission can now contain jwt_vc only, combination of jwt_vp + jwt_vc and sd_jwt submissions.
Added test coverage for edge cases, invalid or missing signatures and attributes
> fix: improve and standardize the DIF Presentation Exchange implementation

- src/castor/Castor.ts
- src/castor/resolver/LongFormPrismDIDResolver.ts
- src/castor/resolver/PeerDIDResolver.ts
- src/castor/types/index.ts
- src/domain/models/DIDDocument.ts
- src/mercury/didcomm/DIDResolver.ts
- src/peer-did/types.ts
- src/plugins/internal/dif/IsCredentialRevoked.ts
- src/pollux/utils/jwt/JWT.ts
- src/pollux/utils/jwt/PKInstance.ts
- src/pollux/utils/jwt/ResolveDID.ts
- tests/castor/PrismDID.test.ts
- tests/plugins/dif/IsCredentialRevoked.test.ts
- tests/pollux/Pollux.revocation.test.ts
We are wrongly resolving the DIDs, which may not be directly impacting our users but our DIDDocuments are wrong in some cases.
Using Prism DID Long form, resolves verificationMethods correctly but their type is set to the curve value which is wrong and should be set to the VerificationMethod type.
See more [Here](https://github.com/hyperledger-identus/sdk-ts/issues/408)
> fix: incorrect handling of verification method affecting did resolution

- src/pollux/utils/jwt/CreateJwt.ts
- src/pollux/utils/jwt/DER.ts
The signed presentation for the credential request is DER-encoded, according to the JWS specification, the signature should not be DER-encoded. Instead, it should be a concatenation of R || S, Base64 URL-safe encoded (as per [RFC 7515, Section 8.1](https://datatracker.ietf.org/doc/html/rfc7515#page-45))
(https://github.com/hyperledger-identus/cloud-agent/issues/1541)
Yes not follow the JWS and fix in cloud-agent to support both DER Encoded and JWS but will require handling both and wont benefit much, since it is JWT we should follow JWS spec
> fix: update signature encoding to follow JWS specification

- src/index.ts
Exposing the DIDcommConnection class to restore the missing functionality
> fix: export DIDCommConnection class on the SDK back to have the ability to establish connections with dids and oob codes

- package-lock.json
- package.json
- src/plugins/internal/dif/PresentationVerify.ts
- tests/plugins/dif/PresentationVerify.test.ts
Simple fix for a bug found during integration tests, when the first input descriptor path is not found but is instead in a secondary path.
Added an improvement in the validateInputDescriptor function and fixed the issue
> fix: clean error instances if we find a valid path + add test rotating paths

- integration-tests/e2e-tests/src/abilities/WalletSdk.ts
Calling `agent.stop` and `store.clear` results in an error as both clear the internal db.
> test(e2e): removing use of store.clear

- integration-tests/e2e-tests/package-lock.json
- integration-tests/e2e-tests/src/abilities/WalletSdk.ts
- package.json
- src/edge-agent/didcomm/CreatePresentationRequest.ts
- src/index.ts
- src/plugins/internal/anoncreds/CredentialIssue.ts
- src/plugins/internal/anoncreds/CredentialOffer.ts
- src/plugins/internal/anoncreds/FetchCredentialDefinition.ts
- src/plugins/internal/anoncreds/FetchSchema.ts
- src/plugins/internal/anoncreds/GetLinkSecret.ts
- src/plugins/internal/anoncreds/PresentationRequest.ts
- src/plugins/internal/anoncreds/PresentationVerify.ts
- src/plugins/internal/anoncreds/index.ts
- src/plugins/internal/anoncreds/plugin.ts
- src/plugins/internal/dif/index.ts
- tests/agent/Agent.anoncreds.test.ts
- tsup.config.js
Moving the Anoncreds code to a separate plugin import / export.
This further decouples the code and should enable downstream builds to completely exclude Anoncreds wasm.
> feat!: Anoncreds moving to plugin export

- .github/workflows/ci.yml
- package-lock.json
- package.json
Fixes rollup wasm build issue https://github.com/npm/cli/issues/4828
> chore: rollup build failure

- release.config.js
Adds `beta` pre release branch to publish to `beta` tag in npmjs
> chore: adds beta prerelease branch

- src/edge-agent/helpers/RunProtocol.ts
- src/index.ts
- src/plugins/internal/didcomm/plugin.ts
- src/plugins/internal/didcomm/tasks/HandleRequestCredential.ts
- tests/agent/HandleRequestCredential.test.ts
handleRequestCredential is a new task that issuers use to Convert a Request credential into a IssueCredential Message automatically.
Will receive the request and create a credential for that request, then, add the credential into a Message.
This is what is used by offline first agent to achieve issuance
> fix: exposing tasks and implement handleRequestCredential

- src/domain/protocols/Payload.ts
- src/plugins/types.ts
Simple task to allow typescript to infer whatever is the response type when calling task plugins
> fix: improve types

- package.json
- src/plugins/internal/dif/index.ts
- src/plugins/internal/oea/index.ts
- tsup.config.js
We are not creating new functionality, but over time we have hidden some of the types used in DIF (presentation exchange) and oea, in order to expose this feature back we're just exposing the DIF and OEA plugin in package json.
> fix: exposing plugins dif + oea types

- src/edge-agent/didcomm/CreateOOBPresentationRequest.ts
- src/index.ts
The SDK so far in ts exports ```SDK.OutOfBandInvitation```, you could put any DIDComm message inside and make it OOB.
I'm just adding a helper class to make creating OOBPresentation easier.
Will not be adding coverage, its just a wrapper for a message and we know it works, take a look at CreateOOBOffer.
> fix: exposing task to create OOB Presentation request
