hyperledger-identus/sdk-ts

- demos/browser/src/App.tsx
Changed the typescript demo to simplify the quick started guide walkthrough.
Added the peerDID in the UI before the agent starts to make it more easy.
Also, we support the SDK to add more than 1 out of band connection without restarting.
ATL-5798
- [*] Self-reviewed the diff
> fix: Improve the Typescript demo and make it easier to go through the qsg

- .github/workflows/ci.yml
- package-lock.json
- package.json
Add breaking changes related to previous commits
> feat!: add npm audit action

- package.json
Attempt to fix yarn issues installing the package, as it can't resolve bundled dependency
No ticket
> fix: adding resolution for yarn

- demos/browser/src/App.tsx
- demos/node/src/index.ts
Simply updating the demos to use the beta mediator the only one working with the latest version of the OAS.
N/A
> fix: Change the demo mediator ID for the beta one.

- .github/workflows/release-docs.yml
- .github/workflows/release.yml
No PR just fixing the configuation for submodules based on https://github.com/actions/checkout documentation.
> fix: wrong CI pipelines for git submodules. Missing With.

- docs/sidebars.js
- package-lock.json
- package.json
- typedoc.js
Adding a sidebar for docusaurus
> fix: add docusaurus sidebar

- package-lock.json
- package.json
Updating apollo to its latest  (v1.2.10) version to fix [ATL-6292]
[ATL-6292]: https://input-output.atlassian.net/browse/ATL-6292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update apollo dependency.

- .github/workflows/ci.yml
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
- .releaserc.yml
- docs/decisions/20231110-sdk-package-release.md
By approving the ADR, rhe flow to release anything from now on becomes the following:
1. Any direct merge to master should be prevented and rejected by engineering if not agreed by the team.
2. Merges should be automatically be made from a feature branch to the RC branch.
Each commit to a RC branch will automatically generate a new release package with semantic-versioning. Releasing the Typescript package will also trigger a new release of the documentation website and deploy to staging.
The task needs this PR merged in master before proceeding, if not , be aware the CI is going to fail generating documentation website and deploying to production.
> fix: approve the ADR + implement the CI changes to release RC packages.

- .releaserc.yml
small fix suggested by allain affecting the npm package release, currently its not being built.
> fix: CI fix, make sure that we build package before publishing into npm

- .github/workflows/release.yml
Fixing CI, the semantic release script is unable to find out the context i just added ./ on the ci task to fix it.
> fix: build script not able to find file.

- release-dev.config.js
Just changing the package name to not include part of the branch name.
> fix: package name update

- integration-tests/e2e-tests/tests/sdk/src/PlutoInMemory.ts
> test: fix peerdid import for e2e

- .github/workflows/release.yml
Adds hyperledger github registry to release pipeline
> ci: adds hyperledger registry for release

- .github/workflows/e2e-tests.yml
- publish.sh
- release.base.config.js
> ci: adds publish shell script

- .github/workflows/release.yml
Fixes the unauthorized signed push tag in release pipeline
```
shortMessage: 'Command failed with exit code 1: git push --tags https://github.com/input-output-hk/atala-prism-wallet-sdk-ts.git HEAD:release/v2.9',
command: 'git push --tags https://github.com/input-output-hk/atala-prism-wallet-sdk-ts.git HEAD:release/v2.9',
escapedCommand: 'git push --tags "https://github.com/input-output-hk/atala-prism-wallet-sdk-ts.git" "HEAD:release/v2.9"',
exitCode: 1,
signal: undefined,
signalDescription: undefined,
stdout: '',
stderr: 'warning: not sending a push certificate since the receiving end does not support --signed push\n' +
'remote: error: GH006: Protected branch update failed for refs/heads/release/v2.9.        \n' +
'remote: error: Changes must be made through a pull request.        \n' + …
```
> ci: adds token parameter on checkout step

- package-lock.json
- rollup/rollup.node.mjs
Fix wasm path in rollup
- [] My PR follows the contribution guidelines of this project
- [] My PR is free of third-party dependencies that don't comply with the [Allowlist](https://toc.hyperledger.org/governing-documents/allowed-third-party-license-policy.html#approved-licenses-for-allowlist)
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have checked the PR title to follow the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/)
> fix: wasm build folder change

- integration-tests/e2e-tests/features/provide_anoncred_proof.feature
- integration-tests/e2e-tests/src/configuration/CloudAgentConfiguration.ts
- integration-tests/e2e-tests/src/workflow/CloudAgentWorkflow.ts
- [] My PR follows the contribution guidelines of this project
- [] My PR is free of third-party dependencies that don't comply with the [Allowlist](https://toc.hyperledger.org/governing-documents/allowed-third-party-license-policy.html#approved-licenses-for-allowlist)
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have checked the PR title to follow the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/)
> test: fixes agent url issue

- .github/ISSUE_TEMPLATE/1-bug-report.yaml
- .github/ISSUE_TEMPLATE/2-feature-request.yaml
- .github/workflows/e2e-tests.yml
- CONTRIBUTING.md
- README.md
- package.json
- tests/apollo/Apollo.test.ts
https://input-output.atlassian.net/browse/ATL-6470
Some visible and non-functional wording updates to Identus.
> fix: updating references to Identus

- docs/README.md
- docs/sidebars.js
- package.json
Fixes issue with docusaurus
- Add script to update readme file
- Update readme id
- Move readme.md to root of docs folder
> docs: fix docusaurus

- package.json
add missing files in package to clean rxdb vulnerabilities
> fix: add missing files in package to clean rxdb vulnerabilities to fix e2e 

- .github/CODEOWNERS
- .github/workflows/e2e-tests.yml
- .github/workflows/release.yml
- integration-tests/e2e-tests/run-local-e2e.sh
- package.json
- publish.sh
Changing tokens and npm namespace to hyperledger
> fix: move to hyperledger namespace

- package-lock.json
- package.json
- src/apollo/Apollo.ts
- src/apollo/utils/Ed25519KeyPair.ts
- src/apollo/utils/Ed25519PrivateKey.ts
- src/apollo/utils/Ed25519PublicKey.ts
- src/apollo/utils/Secp256k1KeyPair.ts
- src/apollo/utils/Secp256k1PrivateKey.ts
- src/apollo/utils/Secp256k1PublicKey.ts
- src/apollo/utils/X25519KeyPair.ts
- src/apollo/utils/X25519PrivateKey.ts
- src/apollo/utils/X25519PublicKey.ts
- tests/apollo/Apollo.test.ts
- tests/apollo/keys/Ed25519.test.ts
- tests/apollo/keys/Secp256k1.test.ts
Updating code to use Identus Apollo
> chore: use identus apollo

- .github/workflows/release.yml
> fix: releasing to HL

- .github/workflows/release.yml
> fix: remove typo in release pipeline

- demos/next/src/actions/types.ts
- demos/next/src/pages/debug.tsx
- demos/next/src/reducers/app.ts
- demos/next/src/reducers/store.ts
improvement in the nextjs demo to make mediator updatable
> fix: make mediator updateable in the nextjs demo

- package-lock.json
- package.json
Updating Apollo library to latest release
> chore: update Apollo lib to latest version

- package-lock.json
- package.json
- release.base.config.js
Fixes issue with npm install and security audit.
> fix: package dependencies found by mixmix (#273)

- README.md
Fixed typo in URL for Edge Agent SDK KMP repo URL
N/A
> docs: corrected Edge Agent SDK KMP repo URL

- package-lock.json
- package.json
- src/domain/utils/randomBytes.ts
Noble Ciphers dependency now needs explicit setting
> fix: noble-ciphers dependency

- .github/CODEOWNERS
fix: simply updating code owners
> fix: update code-owners

- integration-tests/e2e-tests/README.md
Adds more clear goals to run e2e tests
> chore: update e2e readme

- package-lock.json
- package.json
Fixes rollup dependency causing issues
> fix: remove optional rollup dependency causing issues

- README.md
- src/pluto/Pluto.ts
- src/pluto/README.md
https://github.com/hyperledger/identus-edge-agent-sdk-ts/issues/260
Starting a README for Pluto, trying to better explain the options available.
> docs: adding Pluto readme

- package-lock.json
- package.json
- src/edge-agent/didcomm/HandleOOBInvitation.ts
> fix: adding esbuild also as optional missing dependency (#324)

- integration-tests/e2e-tests/features/verify_sdjwt_credential.feature
- integration-tests/e2e-tests/package.json
- integration-tests/e2e-tests/src/Utils.ts
- integration-tests/e2e-tests/src/abilities/WalletSdk.ts
- integration-tests/e2e-tests/src/configuration/CloudAgentConfiguration.ts
- integration-tests/e2e-tests/src/screenplay/Expectations.ts
- integration-tests/e2e-tests/src/steps/EdgeAgentSteps.ts
- integration-tests/e2e-tests/src/workflow/CloudAgentWorkflow.ts
- integration-tests/e2e-tests/src/workflow/EdgeAgentWorkflow.ts
- integration-tests/e2e-tests/yarn.lock
> test: fixes revocation test

- demos/next-sdjwt-workshop/README.md
- demos/next-sdjwt-workshop/package-lock.json
- demos/next-sdjwt-workshop/package.json
- demos/next-sdjwt-workshop/src/actions/index.ts
fix package not installed in workshop
> fix: force in memory for all workshop

- demos/next-sdjwt-workshop/README.md
Small change to the workshop readme to add requirements
> fix: set requirements for workshop

- demos/next-sdjwt-workshop/src/steps/Step1.tsx
> fix: add information for GHRC

- src/edge-agent/didcomm/Agent.ts
Just improving the description for `Agent.acceptInvitation`
> docs: improving Agent.acceptInvitation description

- package-lock.json
Updating a package sub-dependency, which due to vuln severity is blocking builds and merges
> chore: fix package vuln

- docs/cardano/IssuerDID.md
- docs/cardano/index.md
Fix the layout to make the Docusaurus build happy
> chore: apply Docusaurus lint fixes

- src/pluto/rxdb/Store.ts
- tests/pluto/Pluto.Store.test.ts
Adding some basic tests for Pluto Store functionality.
Minor update to Store code to make it more explicit, no functional changes.
> test: adding basic tests for Pluto store

- src/apollo/README.md
- src/castor/README.md
- src/domain/README.md
- src/edge-agent/README.md
- src/mercury/README.md
- src/plugins/PluginManager.ts
- src/plugins/README.md
- src/pollux/README.md
- src/utils/tasks.ts
Adding some simple high level readmes.
> docs: adding high level readmes

- demos/next-sdjwt-workshop/README.md
Fix the broken links on documentation site.
Link to existing ADR (Architecture Decision Record), if any. If relevant, describe other approaches explored and the selected approach. Documenting why the methods were not selected will create a knowledge base for future reference, helping prevent others from revisiting less optimal ideas.
> docs: fix broken links

- src/edge-agent/Agent.MessageEvents.ts
- src/edge-agent/Agent.ts
- src/edge-agent/types/index.ts
Adding a very small change to better type the event listeners making them "type safe"
> fix: better type listeners

- eslint.config.mjs
Removed duplicated entries in eslint config
> fix: removed duplicated entries in eslint config
